// One lesson per day. Each has a "teaser" (the hook shown on Home) and a
// quiz question. The app picks which one is "today's" based on the date,
// so everyone sees the same lesson on the same day, and it wraps back
// around to the start once it reaches the end of the list.
export const LESSONS = [
  {
    emoji: '🪐',
    teaser: "Why Saturn's rings are slowly disappearing",
    prompt: "What are Saturn's rings mostly made of?",
    options: ['Ice and rock', 'Solid metal', 'Liquid gas', 'Sand'],
    correct: 0,
    explanation: "Saturn's rings are countless chunks of ice and rock, some as small as sand, some as big as a house.",
  },
  {
    emoji: '🌌',
    teaser: 'Why the sky is blue, but sunsets are orange',
    prompt: 'What causes the sky to look blue during the day?',
    options: ['Blue light scatters more than other colors', 'The ocean reflects into the sky', 'The sun is actually blue', 'Air is naturally blue'],
    correct: 0,
    explanation: 'Sunlight contains all colors, but the atmosphere scatters shorter, blue wavelengths much more than others, that scattered blue is what fills the sky.',
  },
  {
    emoji: '🧬',
    teaser: "The twisted ladder that stores your body's instructions",
    prompt: 'What shape is a DNA molecule?',
    options: ['Double helix', 'Flat sheet', 'Perfect circle', 'Triangle'],
    correct: 0,
    explanation: "DNA is a double helix, two strands twisted around each other like a spiral staircase, holding the instructions to build and run your body.",
  },
  {
    emoji: '⚡',
    teaser: 'Why nothing can outrun light',
    prompt: 'What happens as an object with mass gets closer to the speed of light?',
    options: ['It takes more and more energy to keep speeding up', 'It gets lighter', 'It passes through time faster', 'Nothing changes'],
    correct: 0,
    explanation: "As mass approaches light speed, it takes exponentially more energy to keep accelerating, which is why nothing with mass can ever fully reach it.",
  },
  {
    emoji: '🍂',
    teaser: "Seasons aren't about how close we are to the sun",
    prompt: "What actually causes Earth's seasons?",
    options: ["Earth's tilt on its axis", 'Earth moving closer and farther from the sun', 'The moon blocking sunlight', 'Clouds changing position'],
    correct: 0,
    explanation: "Earth is tilted about 23.5 degrees, so different parts of the planet get more or less direct sunlight throughout the year, that tilt drives the seasons, not distance from the sun.",
  },
  {
    emoji: '🌿',
    teaser: 'How plants turn sunlight into food',
    prompt: 'What do plants take in to make their own food through photosynthesis?',
    options: ['Carbon dioxide and water', 'Oxygen and soil', 'Nitrogen and sand', 'Just sunlight'],
    correct: 0,
    explanation: 'Plants combine carbon dioxide from the air with water from their roots, using sunlight as energy, to make sugar for food and release oxygen as a byproduct.',
  },
  {
    emoji: '🕳️',
    teaser: 'The place where not even light can escape',
    prompt: 'What is a black hole?',
    options: ['A region where gravity is too strong for even light to escape', 'An empty patch of space with nothing in it', 'A dying star that turns into ice', 'A hole in the ozone layer'],
    correct: 0,
    explanation: "A black hole forms when matter collapses into a small enough space that its gravity becomes powerful enough to trap even light, nothing that crosses its edge gets back out.",
  },
  {
    emoji: '🧪',
    teaser: 'The real logic behind the periodic table',
    prompt: 'How is the periodic table of elements organized?',
    options: ['By number of protons in each atom', 'Alphabetically', 'By how common each element is', 'By color'],
    correct: 0,
    explanation: 'Elements are ordered by atomic number, the number of protons in each atom, which is also what makes each element chemically unique.',
  },
  {
    emoji: '🛡️',
    teaser: 'Your body has its own tiny security guards',
    prompt: 'What is an antibody?',
    options: ['A protein your immune system makes to tag invaders', 'A type of vitamin', 'A blood cell that carries oxygen', 'A muscle fiber'],
    correct: 0,
    explanation: 'Antibodies are proteins your immune system builds to latch onto specific germs, marking them so the rest of your immune system can destroy them.',
  },
  {
    emoji: '🌍',
    teaser: "The ground under your feet is actually moving",
    prompt: "What is Earth's outer crust broken up into?",
    options: ['Large moving plates', 'One solid piece', 'Floating islands of rock', 'Layers of ice'],
    correct: 0,
    explanation: "Earth's crust is split into tectonic plates that slowly drift over time, their movement causes earthquakes, volcanoes, and even shapes entire continents.",
  },
  {
    emoji: '🔭',
    teaser: 'Planets exist way beyond our own solar system',
    prompt: 'What is an exoplanet?',
    options: ['A planet that orbits a star outside our solar system', 'A moon of Jupiter', 'A planet with no atmosphere', 'An asteroid shaped like a planet'],
    correct: 0,
    explanation: 'An exoplanet is any planet orbiting a star other than our sun. Thousands have been discovered, some even sitting in a "habitable zone" where liquid water could exist.',
  },
  {
    emoji: '🦎',
    teaser: 'How species change over time, without anyone planning it',
    prompt: 'What mechanism drives evolution by natural selection?',
    options: ['Helpful traits are more likely to get passed on', 'Animals choose to evolve when they need to', 'Random mutations always make a species better', 'Species change to match what they want to become'],
    correct: 0,
    explanation: 'Individuals with traits that help them survive and reproduce tend to pass those traits on more often, over many generations, that shifts the whole population.',
  },
  {
    emoji: '💨',
    teaser: "The air you're breathing isn't mostly oxygen",
    prompt: "What's the most abundant gas in Earth's atmosphere?",
    options: ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Hydrogen'],
    correct: 0,
    explanation: "Nitrogen makes up about 78% of the air around you. Oxygen, the gas we actually breathe in to survive, is only about 21%.",
  },
  {
    emoji: '☢️',
    teaser: 'How scientists date fossils and ancient rock',
    prompt: 'What does "half-life" mean for a radioactive element?',
    options: ['The time it takes for half of it to decay', 'The point where it becomes harmless', 'Half of its total weight', 'The middle of its lifespan on Earth'],
    correct: 0,
    explanation: "A half-life is the time it takes for half of a radioactive sample to decay into something else. Because it's steady and predictable, it's used to date fossils and rocks.",
  },
  {
    emoji: '✨',
    teaser: "A light-year isn't actually a measure of time",
    prompt: 'What does a light-year measure?',
    options: ['Distance', 'Time', 'Brightness', 'Temperature'],
    correct: 0,
    explanation: 'A light-year is the distance light travels in one year, about 5.9 trillion miles. Despite the name, it measures distance, not time.',
  },
  {
    emoji: '🔋',
    teaser: 'The tiny power plants inside every one of your cells',
    prompt: 'What is the main job of mitochondria in a cell?',
    options: ['Producing energy for the cell', 'Storing genetic information', 'Protecting the cell from viruses', 'Making proteins'],
    correct: 0,
    explanation: 'Mitochondria convert nutrients into a usable energy molecule called ATP, which is why they\'re often called the "powerhouse of the cell."',
  },
  {
    emoji: '🧊',
    teaser: 'Ice breaks a rule that almost every other solid follows',
    prompt: 'Why do ice cubes float in water?',
    options: ['Water expands and gets less dense when it freezes', 'Ice is warmer than water', 'Air gets trapped inside ice cubes', 'Water molecules shrink when frozen'],
    correct: 0,
    explanation: "Most substances get denser as they cool, but water actually expands when it freezes, making ice less dense than liquid water, so it floats instead of sinking.",
  },
  {
    emoji: '🚨',
    teaser: 'Why a siren sounds different as it passes you',
    prompt: 'What is the Doppler effect?',
    options: ['A change in wave frequency caused by motion', 'A type of echo in mountains', 'The bending of light through water', 'A change in sound volume over distance'],
    correct: 0,
    explanation: "As a sound source moves toward or away from you, the wave frequency shifts, that's why a siren sounds higher-pitched approaching and lower-pitched leaving.",
  },
  {
    emoji: '🌦️',
    teaser: "Weather and climate aren't the same thing",
    prompt: "What's the difference between weather and climate?",
    options: ['Weather is short-term, climate is a long-term pattern', 'They mean exactly the same thing', 'Weather only refers to rain', 'Climate changes every day, weather doesn\'t'],
    correct: 0,
    explanation: "Weather is what's happening right now or this week. Climate is the average pattern of weather in a place over many years.",
  },
  {
    emoji: '🧠',
    teaser: 'The cells that carry every thought you have',
    prompt: 'What is a neuron?',
    options: ['A nerve cell that sends signals through your body', 'A type of blood cell', 'A muscle fiber', 'A hormone made by the brain'],
    correct: 0,
    explanation: 'Neurons are specialized cells that send electrical and chemical signals to each other, they\'re how your brain and nervous system communicate with the rest of your body.',
  },
];
